public class Variables
{
    public static void main(String[] args)
    {
        // 1. Declare and initialize a variable for each scenario:

        // A friend's name
        String friendName = "Anish";
        // Your lucky number
        int luckyNumber = 7;
        // Whether or not you are you a morning person (the value
        // should be either `true` or `false`)
        boolean morningPerson = false;
        // Your favorite snack
        String favSnack = "chips";
        // The price of your favorite snack
        double snackPrice = 3.99;

        // 2. Print out each variable:
        System.out.println(friendName);
        System.out.println(luckyNumber);
        System.out.println(morningPerson);
        System.out.println(favSnack);
        System.out.println(snackPrice);

    }
}