public class Signature {


    public static void main(String[] args) {
        char firstInitial = 'A';
    char secondInitial = 'R';

    int month = 8;
    int day = 29;
    int year = 2025;

        System.out.println("Initials:");
        System.out.println(firstInitial);
        System.out.println(secondInitial);
        System.out.println("");
        System.out.println("Date:");
        System.out.println(month);
        System.out.println(day);
        System.out.println(year);
    }
}